CREATE TABLE IF NOT EXISTS question
(
    id    BIGSERIAL PRIMARY KEY,
    day DATE NOT NULL,
    at TIME NOT NULL,
    name  VARCHAR(28) NOT NULL,
    token  BIGINT NOT NULL,
    uid  VARCHAR(100) NOT NULL,
    data TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS answer
(
    id    BIGSERIAL PRIMARY KEY,
    day DATE NOT NULL,
    at TIME NOT NULL,
    uid  VARCHAR(100) NOT NULL,
    data TEXT NOT NULL
);